version: '3.7'

services:

  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    depends_on:
      - mongo
      - backend

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    depends_on:
      - backend

volumes:
  mongo_data:
